apiVersion: v1
kind: Pod
metadata:
  name: pod-demo2
  namespace: test
  labels:
    enivronment: development
    app: nginx
spec:
  containers:
  - name: nginx
    image: quay.io/gauravkumar9130/nginx    
